files:
  - source: /locales/th/translation.json
    translation: /locales/%two_letters_code%/translation.json
  - source: /src/data/about/about.json
    translation: /locales/%two_letters_code%/about.json
